# SimpleGroups by Perotin


default-prefix: "&7[Default]&f "



messages:
  only-players: "Only players can use this command."
  current-group: "Your current group: {group}, Time remaining: {time}"
  no-time: "None"
  no-group: "You are not in any group currently."
  usage-create: "Usage: /sg create <group-name> <optional: inherit> <optional: name>"
  group-created: "Group {group} created successfully."
  usage-setplayer: "Usage: /sg setplayer <group-name> <player-name>"
  group-not-exist: "Group {group} does not exist."
  player-not-online: "Player {player} is not online."
  player-added: "{player} has been added to group {group}."
  unknown-command: "Unknown command. Use /sg create or /sg setplayer."
